export const ACCOUNTS_CHANGE_VISIBILITY = "ACCOUNTS_CHANGE_VISIBILITY";
export const ACCOUNTS_UPDATE_BALANCES = "ACCOUNTS_UPDATE_BALANCES";
export const ACCOUNTS_UPDATE_PRICES = "ACCOUNTS_UPDATE_PRICES:";
